- name: Do an yum update & upgrade
  become: yes
  yum:
    name: '*'
    state: latest

- name: Connect amazon repo
  become: yes
  yum:
    name: amazon-linux-extras install epel
    state: present

- name: Install required packages
  become: yes
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - sudo