- name: Do an yum update & upgrade
  become: yes
  yum:
    name: '*'
    state: latest

- name: Install EPEL
  package:
    name: epel-release
    state: present
  when: ansible_distribution == "CentOS" or ansible_distribution=="RedHat"